### ISSUE TITLE
Inefficient implementation

### ISSUE THREAD

**Issue by RReverser** [roman01la/js-head#1]
Such implementation is very inefficient - it still goes through entire iterable. E.g. if I pass custom iterator like this:

```javascript
function *iter() {
  console.log(1);
  yield 1;
  console.log(2);
  yield 2;
  console.log(3);
  yield 3;
}

head(iter());
```

I'll get all of `1`, `2` and `3` in the console. Effect for deeper/bigger iterations will be even worse.

(Moreover - it converts the rest into a separately created temporary array which is never used)

**Comment by roman01la** [comment]
My use case is that this way it's possible to get first element from any iterable. If there's another way to achieve exact same flexibility, you are welcome to submit it.

**Comment by RReverser** [comment]
Of course - just use `for-of` which also works with any iterable and which you can `break` precisely where you want instead of converting everything into an array.

**Comment by roman01la** [comment]
That's cool, never thought about it. Thanks! 😀

**Comment by RReverser** [comment]
Btw, you could actually achieve similar effect (although it would still include small extra conversion) by just not including the rest part which you don't need:

```javascript
export default ([x]) => x;
```

**Comment by roman01la** [comment]
Will keep that in mind. Thanks!
